( function( $ ) {

	// Localized variables
	var headers = sccTocwPageElements.phpHeaders;
	var scrollToOffset = parseInt( sccTocwOpts.scrollToOffset );
	var smoothScrollTime = parseInt( sccTocwOpts.smoothScrollTime );

	// This starts at 0, because h1 title is included in document... maybe...
	var headerId = 0;

	// Set 0-second / instantaneous smooth-scroll time to 1 millisecond, because .animate doesn't like 0
	if ( 0 === smoothScrollTime ) {
		smoothScrollTime = 1; // Basically instantaneous
	}

	// Take admin bar height into account and add it to the scroll-to offset
	function determineWpAdminBarHeight() {
		scrollToOffset = parseInt(sccTocwOpts.scrollToOffset);
		var wpAdBar = $( '#wpadminbar' );

		if ( wpAdBar.length ) {
			var adminBarHeight = parseInt(wpAdBar.height());
			scrollToOffset += adminBarHeight;
		}
	}

	// Determine additional offset height on page load
	$( document ).ready(function() {
		determineWpAdminBarHeight();
	});

	// Determine additional offset height on window resize
	$( window ).resize(function() {
		determineWpAdminBarHeight();
	})
	
	// Find all headers in body and add them to the array
	$( 'body' ).find( 'h1, h2, h3, h4, h5, h6' ).each( function() {

		// PHP and JS apostrophes can be different, so this converts JS apostrophe to PHP version
		var header_js_text = $( this ).text();
		var header_js_text = header_js_text.replace( '’', '\'' );

		// Only add h tag if there are more to add and if the text equal each other
		// There can be a slight issue with themes that load page / post titles twice, but the other headings in the content should be unaffected
		if (
			headerId < headers.length &&
			headers[headerId]['header_content'] === header_js_text
		) {

			headers[headerId]['obj'] = $( this );
			headerId++;

		}

	});

	// Find the links generated by PHP function
	$( '.scc-tocw-link' ).click( function() {

		var clickedHeaderId = $( this ).attr( 'data-scc-tocw-id' );
		var clickedHeader = headers[clickedHeaderId].obj;

		$( 'html, body' ).animate( {

			scrollTop: $( clickedHeader ).offset().top -( scrollToOffset ),

		}, smoothScrollTime );

	});

} )( jQuery );